# Generated by Django 2.0.1 on 2019-10-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('course', models.CharField(max_length=25)),
                ('Completion_Date', models.CharField(max_length=25)),
                ('Date_joining', models.CharField(max_length=25)),
                ('Course_fee', models.CharField(max_length=25)),
                ('Instructor', models.CharField(max_length=25)),
                ('Aadhar_no', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone_no', models.CharField(max_length=25)),
                ('remark', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Register_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=25)),
                ('Phone_no', models.CharField(max_length=10)),
                ('Course', models.CharField(max_length=25)),
                ('Source', models.CharField(max_length=25)),
                ('Leadstatus', models.CharField(max_length=25)),
                ('Date_demo', models.CharField(max_length=25)),
                ('Counsler', models.CharField(max_length=25)),
                ('Remark', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
