# Generated by Django 2.0.1 on 2019-10-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191012_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register_user',
            new_name='Register',
        ),
    ]
